export const ICONS = {
  add: "/icon/add.png",
  archer: "/icon/archer.png",
  axe: "/icon/axe.png",
  balance: "/icon/balance.png",
  calendar: "/icon/calendar.png",
  chat: "/icon/chat.png",
  cloud: "/icon/cloud.png",
  cloudy: "/icon/cloudy.png",
  crop: "/icon/crop.png",
  degree: "/icon/degree.png",
  docs: "/icon/docs.png",
  flag: "/icon/flag.png",
  fourFinger: "/icon/four-finge.png",
  ghost: "/icon/ghost.png",
  heartEyes: "/icon/heart-eyes.png",
  hearth: "/icon/hearth.png",
  home: "/icon/home.png",
  hourglass: "/icon/hourglass.png",
  label: "/icon/label.png",
  leftDownArrow: "/icon/left-down-arrow.png",
  letter: "/icon/letter.png",
  letter2: "/icon/letter2.png",
  note: "/icon/note.png",
  partyCard: "/icon/party-card.png",
  pixelated: "/icon/pixelated (1).png",
  play: "/icon/play.png",
  rain: "/icon/rain.png",
  rightDown: "/icon/right-down.png",
  send: "/icon/send.png",
  sheet: "/icon/sheet.png",
  slaughter: "/icon/slaughter.png",
  snowflake: "/icon/snowflake.png",
  sreakhot: "/icon/sreakhot.png",
  star: "/icon/star.png",
  surprise: "/icon/surprise.png",
  target: "/icon/target.png",
  tick: "/icon/tick.png",
  tree: "/icon/tree.png",
  trophy: "/icon/trophy.png",
  user: "/icon/user.png",
  wallet: "/icon/wallet.png",
} as const;

export type IconName = keyof typeof ICONS;
