export type KategoriAdi = "sayisal" | "ea" | "dil";

export interface YksDers {
  key: string;
  isim: string;
  icon: string;
  renk: string;
  tytKonular: string[];
  aytKonular: string[];
}

// ─── Tüm dersler (yks_konular.json'a göre) ───────────────────────────────────
export const DERSLER: Record<string, YksDers> = {
  turkce: {
    key: "turkce",
    isim: "Türkçe",
    icon: "📝",
    renk: "#E74C3C",
    tytKonular: [
      "Sözcükte Anlam",
      "Cümlede Anlam",
      "Paragraf",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcük Türleri",
      "Fiilimsiler",
      "Cümlenin Ögeleri",
      "Cümle Türleri",
      "Anlatım Bozuklukları",
      "Dil ve Anlatım",
    ],
    aytKonular: [],
  },
  matematik: {
    key: "matematik",
    isim: "Matematik",
    icon: "🧮",
    renk: "#3498DB",
    tytKonular: [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme",
      "EBOB - EKOK",
      "Ondalık Sayılar",
      "Kesirler",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran Orantı",
      "Denklem Çözme",
      "Problemler (Yaş, Hız, İşçi, Yüzde, Kar-Zarar, Karışım, Hareket)",
      "Kümeler",
      "Mantık",
      "Fonksiyonlar (Temel)",
      "Sayma ve Olasılık (Temel)",
    ],
    aytKonular: [
      "Fonksiyonlar",
      "Logaritma",
      "Diziler (Aritmetik, Geometrik)",
      "Limit ve Süreklilik",
      "Türev",
      "İntegral",
      "Trigonometri",
      "Karmaşık Sayılar",
      "Permütasyon ve Kombinasyon",
      "Binom Açılımı",
      "Olasılık",
      "İstatistik",
      "Matrisler ve Determinant",
      "Vektörler",
    ],
  },
  geometri: {
    key: "geometri",
    isim: "Geometri",
    icon: "📐",
    renk: "#1A5276",
    tytKonular: [
      "Temel Geometri Kavramları",
      "Açılar",
      "Üçgenler",
      "Dörtgenler",
      "Çokgenler",
      "Çember ve Daire",
      "Katı Cisimler (Temel)",
    ],
    aytKonular: [
      "Analitik Geometri (Nokta, Doğru)",
      "Çemberin Analitik İncelenmesi",
      "Konikler (Parabol, Elips, Hiperbol)",
      "Üçgenler (İleri)",
      "Dörtgenler (İleri)",
      "Çember ve Daire (İleri)",
      "Katı Cisimler (Prizmalar, Piramitler, Küre, Koni, Silindir)",
      "Dönüşüm Geometrisi",
      "Koordinat Uzayı",
    ],
  },
  tarih: {
    key: "tarih",
    isim: "Tarih",
    icon: "🏛️",
    renk: "#8B5E3C",
    tytKonular: [
      "Tarih Bilimi",
      "Uygarlığın Doğuşu",
      "İlk Türk Devletleri",
      "İslam Tarihi ve Uygarlığı",
      "Türk-İslam Devletleri",
      "Osmanlı Devleti Kuruluş ve Yükseliş",
      "Osmanlı Devleti Duraklama ve Gerileme",
      "Osmanlı Devleti Dağılma Dönemi",
      "Kurtuluş Savaşı",
      "Türkiye Cumhuriyeti Kuruluş Dönemi",
    ],
    aytKonular: [
      "Osmanlı Tarihi (Ayrıntılı)",
      "Osmanlı Kültür ve Medeniyeti",
      "Siyasi Tarih (19-20. yy)",
      "1. Dünya Savaşı",
      "Milli Mücadele Dönemi",
      "Türk İnkılabı",
      "Atatürk İlkeleri",
      "Atatürk Dönemi Türk Dış Politikası",
      "2. Dünya Savaşı ve Sonrası",
      "Yakın Dönem Türk Tarihi",
      "Dünya Tarihi (Genel)",
      "Demokrasi ve Türkiye",
    ],
  },
  cografya: {
    key: "cografya",
    isim: "Coğrafya",
    icon: "🌍",
    renk: "#1ABC9C",
    tytKonular: [
      "Doğal Sistemler",
      "Beşeri Sistemler",
      "Küresel Ortam",
      "Çevre ve Toplum",
      "Coğrafi Beceriler",
      "Türkiye'nin Genel Coğrafi Özellikleri",
      "Nüfus ve Yerleşme",
      "Türkiye Ekonomisi",
    ],
    aytKonular: [
      "Doğal Sistemler (İleri)",
      "Beşeri Sistemler (İleri)",
      "Mekansal Bir Sentez: Türkiye",
      "Küresel Ortam: Bölgeler ve Ülkeler",
      "Çevre ve Toplum (İleri)",
      "Doğal Afetler",
      "Sektörel Dağılım ve Ekonomi",
      "Uluslararası Ulaşım ve Ticaret",
      "Türkiye'nin Jeopolitik Konumu",
    ],
  },
  felsefe: {
    key: "felsefe",
    isim: "Felsefe",
    icon: "🤔",
    renk: "#9B59B6",
    tytKonular: [
      "Felsefeye Giriş",
      "Bilgi Felsefesi",
      "Varlık Felsefesi",
      "Ahlak Felsefesi",
      "Siyaset Felsefesi",
      "Din Felsefesi",
      "Sanat Felsefesi",
      "Bilim Felsefesi",
    ],
    aytKonular: [
      "Felsefi Akımlar",
      "Bilgi Felsefesi (İleri)",
      "Varlık Felsefesi (İleri)",
      "Ahlak Felsefesi (İleri)",
      "Siyaset Felsefesi (İleri)",
      "Din Felsefesi (İleri)",
      "Sanat Felsefesi (İleri)",
      "Bilim Felsefesi (İleri)",
      "Mantık",
    ],
  },
  din_kulturu: {
    key: "din_kulturu",
    isim: "Din Kültürü",
    icon: "🕌",
    renk: "#D4A96A",
    tytKonular: [
      "İnanç",
      "İbadet",
      "Hz. Muhammed",
      "Kur'an ve Yorumu",
      "Ahlak",
      "İslam Düşüncesinde Yorumlar",
      "Din, Kültür ve Medeniyet",
    ],
    aytKonular: [],
  },
  fizik: {
    key: "fizik",
    isim: "Fizik",
    icon: "⚡",
    renk: "#2980B9",
    tytKonular: [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Hareket ve Kuvvet",
      "Enerji",
      "Isı ve Sıcaklık",
      "Elektrostatik",
      "Elektrik",
      "Dalgalar",
      "Optik (Temel)",
    ],
    aytKonular: [
      "Vektörler",
      "Kinematik",
      "Dinamik",
      "İş, Güç, Enerji",
      "İtme ve Momentum",
      "Tork ve Denge",
      "Basit Harmonik Hareket",
      "Gravitasyon",
      "Katı Cisimlerin Mekaniği",
      "Elektrik ve Manyetizma",
      "Dalgalar ve Ses",
      "Optik",
      "Gazlar",
      "Isı ve Termodinamik",
      "Atom ve Çekirdek Fiziği",
      "Modern Fizik",
    ],
  },
  kimya: {
    key: "kimya",
    isim: "Kimya",
    icon: "⚗️",
    renk: "#27AE60",
    tytKonular: [
      "Kimya Bilimine Giriş",
      "Atom ve Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Halleri",
      "Doğa ve Kimya",
      "Karışımlar",
      "Asitler, Bazlar ve Tuzlar (Temel)",
      "Kimya Her Yerde",
    ],
    aytKonular: [
      "Atomun Yapısı ve Periyodik Sistem",
      "Kimyasal Bağlar",
      "Gazlar",
      "Sıvılar ve Katılar",
      "Çözeltiler",
      "Kimyasal Tepkimeler",
      "Kimyasal Denge",
      "Asit-Baz Dengesi",
      "Çözünürlük Dengesi",
      "Kimyasal Kinetik",
      "Elektrokimya",
      "Kimyasal Hesaplamalar",
      "Organik Kimya",
      "Önemli Organik Bileşikler",
      "Polimer, Karbonhidrat, Yağ, Protein",
    ],
  },
  biyoloji: {
    key: "biyoloji",
    isim: "Biyoloji",
    icon: "🧬",
    renk: "#7EC850",
    tytKonular: [
      "Canlıların Ortak Özellikleri",
      "Hücre",
      "Canlıların Sınıflandırılması",
      "Ekosistem Ekolojisi",
      "Güncel Çevre Sorunları",
      "Bitki ve Hayvan Doku",
      "Sindirim Sistemi",
      "Dolaşım Sistemi",
      "Solunum Sistemi",
      "Boşaltım Sistemi",
    ],
    aytKonular: [
      "Hücre",
      "Hücre Bölünmeleri",
      "Kalıtım",
      "Genetik Mühendisliği ve Biyoteknoloji",
      "Canlıların Sınıflandırılması (İleri)",
      "Dolaşım Sistemi",
      "Solunum Sistemi",
      "Sinir Sistemi",
      "Hormonlar ve Endokrin Sistem",
      "Üreme Sistemi",
      "Bağışıklık Sistemi",
      "Bitki Biyolojisi",
      "Ekosistem ve Çevre",
      "Evrim",
    ],
  },
  turk_dili_edebiyati: {
    key: "turk_dili_edebiyati",
    isim: "Türk Dili ve Edebiyatı",
    icon: "📖",
    renk: "#C0392B",
    tytKonular: [],
    aytKonular: [
      "Şiir Bilgisi",
      "Şiir Türleri",
      "Düz Yazı Türleri",
      "Divan Edebiyatı",
      "Halk Edebiyatı",
      "Tanzimat Edebiyatı",
      "Servet-i Fünun Edebiyatı",
      "Fecr-i Ati Edebiyatı",
      "Milli Edebiyat Dönemi",
      "Cumhuriyet Dönemi Türk Edebiyatı",
      "Roman, Hikaye, Tiyatro, Şiir Akımları",
      "Söz Sanatları",
    ],
  },
  yabanci_dil: {
    key: "yabanci_dil",
    isim: "Yabancı Dil",
    icon: "🌐",
    renk: "#E67E22",
    tytKonular: [],
    aytKonular: [],
  },
};

// ─── TYT dersleri (tüm kategoriler için aynı) ─────────────────────────────────
export const TYT_DERSLER = [
  "turkce",
  "matematik",
  "geometri",
  "tarih",
  "cografya",
  "felsefe",
  "din_kulturu",
  "fizik",
  "kimya",
  "biyoloji",
];

// ─── TYT/AYT yapısı her kategori için ────────────────────────────────────────
export interface KategoriYapi {
  label: string;
  icon: string;
  renk: string;
  aciklama: string;
  tyt: string[];
  ayt: string[];
}

export const KATEGORILER: Record<KategoriAdi, KategoriYapi> = {
  sayisal: {
    label: "Sayısal",
    icon: "🔬",
    renk: "#3498DB",
    aciklama: "MF puan türü · Matematik ağırlıklı",
    tyt: TYT_DERSLER,
    ayt: ["matematik", "geometri", "fizik", "kimya", "biyoloji"],
  },
  ea: {
    label: "Eşit Ağırlık",
    icon: "⚖️",
    renk: "#9B59B6",
    aciklama: "TM puan türü · Sözel + Sayısal",
    tyt: TYT_DERSLER,
    ayt: ["matematik", "geometri", "turk_dili_edebiyati", "tarih", "cografya", "felsefe"],
  },
  dil: {
    label: "Dil",
    icon: "🌍",
    renk: "#E67E22",
    aciklama: "Dil puan türü · Yabancı Dil ağırlıklı",
    tyt: TYT_DERSLER,
    ayt: ["turk_dili_edebiyati", "tarih", "cografya", "felsefe", "yabanci_dil"],
  },
};
