export type KategoriAdi = "sayisal" | "ea" | "dil";

export interface YksDers {
  key: string;
  isim: string;
  icon: string;
  renk: string;
  tytKonular: string[];
  aytKonular: string[];
  kpssKonular?: string[];
  kpssGrup?: "gy" | "gk"; // Genel Yetenek / Genel Kültür
}

// ─── Tüm dersler (2026 YKS + KPSS Konu Dağılımları) ─────────────────────────
export const DERSLER: Record<string, YksDers> = {
  turkce: {
    key: "turkce",
    isim: "Türkçe",
    icon: "📝",
    renk: "#E74C3C",
    tytKonular: [
      "Sözcükte Anlam",
      "Cümlede Anlam",
      "Paragrafta Anlam",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcükte Yapı",
      "Sözcük Türleri",
      "İsimler",
      "Zamirler",
      "Sıfatlar",
      "Zarflar",
      "Edat – Bağlaç – Ünlem",
      "Fiil, Ek Fiil, Fiilimsi",
      "Sözcük Grupları",
      "Cümlenin Ögeleri",
      "Cümle Türleri",
      "Anlatım Bozukluğu",
    ],
    aytKonular: [],
    // KPSS GY — Türkçe: 30 soru (4 sözel mantık dahil)
    kpssKonular: [
      "Sözcükte Anlam (1 soru)",
      "Cümlede Anlam (2 soru)",
      "Paragrafta Anlam (15 soru)",
      "Ses Olayları (1 soru)",
      "Yapı Bilgisi ve Ekler (1 soru)",
      "Sözcük Türleri (2 soru)",
      "Cümlenin Ögeleri ve Cümle Bilgisi (1 soru)",
      "Yazım Kuralları (1 soru)",
      "Noktalama İşaretleri (1 soru)",
      "Anlatım Bozuklukları (1 soru)",
      "Sözel Mantık (4 soru)",
    ],
    kpssGrup: "gy",
  },

  matematik: {
    key: "matematik",
    isim: "Matematik",
    icon: "🧮",
    renk: "#3498DB",
    tytKonular: [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme",
      "EBOB – EKOK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran Orantı",
      "Denklem Çözme",
      "Problemler (Sayı, Kesir, Yüzde, Kar-Zarar, Karışım, Grafik, Yaş, İşçi, Hız)",
      "Kümeler ve Kartezyen Çarpım",
      "Mantık",
      "Fonksiyonlar",
      "Polinomlar",
      "2. Dereceden Denklemler",
      "Permütasyon ve Kombinasyon",
      "Olasılık",
      "İstatistik",
    ],
    aytKonular: [
      "Binom",
      "Logaritma",
      "Limit",
      "Diziler",
      "Türev",
      "İntegral",
      "Trigonometri",
      "Karmaşık Sayılar",
      "2. Dereceden Eşitsizlikler",
      "Parabol",
    ],
    // KPSS GY — Matematik: 27 soru (4–6 sayısal mantık dahil)
    kpssKonular: [
      "Temel Kavramlar (3 soru)",
      "Rasyonel Sayılar ve Ondalık Sayılar (2 soru)",
      "Basit Eşitsizlikler (1 soru)",
      "Mutlak Değer (1 soru)",
      "Üslü Sayılar (2 soru)",
      "Köklü Sayılar (1 soru)",
      "Çarpanlara Ayırma (1 soru)",
      "Denklem Çözme (1 soru)",
      "Sayı Problemleri (1 soru)",
      "Yaş Problemleri (1 soru)",
      "Hareket Problemleri (1 soru)",
      "Yüzde, Kar-Zarar, Faiz Problemleri (2 soru)",
      "Bağıntı ve Fonksiyon (1 soru)",
      "İşlem ve Modüler Aritmetik (1 soru)",
      "Olasılık (1 soru)",
      "Sayısal Mantık (6 soru)",
    ],
    kpssGrup: "gy",
  },

  geometri: {
    key: "geometri",
    isim: "Geometri",
    icon: "📐",
    renk: "#1A5276",
    tytKonular: [
      "Temel Kavramlar",
      "Doğruda Açılar ve Üçgende Açılar",
      "Özel Üçgenler (Dik, İkizkenar, Eşkenar)",
      "Açıortay ve Kenarortay",
      "Üçgende Alan",
      "Üçgende Benzerlik",
      "Açı Kenar Bağıntıları",
      "Çokgenler",
      "Özel Dörtgenler (Deltoid, Paralelkenar, Eşkenar Dörtgen, Dikdörtgen, Kare, İkizkenar Yamuk)",
      "Çember ve Daire",
      "Noktanın Analitiği ve Doğrunun Analitiği",
      "Katı Cisimler (Prizma, Küp, Silindir, Piramit, Koni, Küre)",
      "Dönüşümlerle Geometri",
    ],
    aytKonular: [
      "Çemberin Analitiği",
    ],
    // KPSS GY — Geometri: 3 soru
    kpssKonular: [
      "Özel Üçgenler (1 soru)",
      "Dörtgenler ve Çokgenler (1 soru)",
      "Analitik Geometri (1 soru)",
    ],
    kpssGrup: "gy",
  },

  tarih: {
    key: "tarih",
    isim: "Tarih",
    icon: "🏛️",
    renk: "#8B5E3C",
    tytKonular: [
      "Tarih ve Zaman",
      "İnsanlığın Doğuşu ve İlk Uygarlıklar",
      "Orta Çağda Dünya ve Türkler",
      "İslam Medeniyetinin Doğuşu",
      "Türklerin İslamiyet'i Kabulü ve İlk Türk İslam Devletleri",
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
      "Beylikten Devlete Osmanlı Siyaseti (1302–1453)",
      "Devletleşme Sürecinde Savaşçılar ve Askerler",
      "Beylikten Devlete Osmanlı Medeniyeti",
      "Dünya Gücü Osmanlı (1453–1595)",
      "Sultan ve Osmanlı Merkez Teşkilatı",
      "Klasik Çağda Osmanlı Toplum Düzeni",
      "Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti (1595–1774)",
      "Değişim Çağında Avrupa ve Osmanlı",
      "Uluslararası İlişkilerde Denge Stratejisi (1774–1914)",
      "Devrimler Çağında Değişen Devlet-Toplum İlişkileri",
      "Sermaye ve Emek",
      "XIX. ve XX. Yüzyılda Değişen Gündelik Hayat",
      "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
      "Milli Mücadele",
      "Atatürkçülük ve Türk İnkılabı",
    ],
    aytKonular: [
      "İki Savaş Arasındaki Dönemde Türkiye ve Dünya",
      "II. Dünya Savaşı Sürecinde Türkiye ve Dünya",
      "II. Dünya Savaşı Sonrasında Türkiye ve Dünya",
      "Toplumsal Devrim Çağında Dünya ve Türkiye",
      "21. Yüzyılın Eşiğinde Türkiye ve Dünya",
    ],
    // KPSS GK — Tarih: 27 soru
    kpssKonular: [
      "İslamiyet Öncesi Türk Tarihi (1 soru)",
      "İlk Türk İslam Devletleri (2 soru)",
      "Osmanlı Devleti Siyasi Tarihi (6 soru)",
      "Osmanlı Devleti Kültür ve Uygarlık (3 soru)",
      "Kurtuluş Savaşı Hazırlık Dönemi (4 soru)",
      "Kurtuluş Savaşı Cepheleri (3 soru)",
      "Atatürk Devrim Tarihi (2 soru)",
      "Atatürk Dönemi İç ve Dış Politika (2 soru)",
      "Atatürk İlkeleri (1 soru)",
      "Çağdaş Türk ve Dünya Tarihi (3 soru)",
    ],
    kpssGrup: "gk",
  },

  cografya: {
    key: "cografya",
    isim: "Coğrafya",
    icon: "🌍",
    renk: "#1ABC9C",
    tytKonular: [
      "Doğa ve İnsan",
      "Dünya'nın Şekli ve Hareketleri",
      "Coğrafi Konum",
      "Harita Bilgisi",
      "Atmosfer ve Sıcaklık",
      "İklimler",
      "Basınç ve Rüzgarlar",
      "Nem, Yağış ve Buharlaşma",
      "İç Kuvvetler / Dış Kuvvetler",
      "Su, Toprak ve Bitkiler",
      "Nüfus",
      "Göç",
      "Yerleşme",
      "Türkiye'nin Yer Şekilleri",
      "Ekonomik Faaliyetler",
      "Bölgeler",
      "Uluslararası Ulaşım Hatları",
      "Çevre ve Toplum",
      "Doğal Afetler",
    ],
    aytKonular: [
      "Ekosistem",
      "Doğadaki Ekstrem Olaylar",
      "İlk Medeniyet ve Şehirler",
      "Nüfus Politikaları",
      "Türkiye'de Nüfus ve Yerleşme",
      "Ekonomik Faaliyetler",
      "Göç ve Şehirleşme",
      "Türkiye Ekonomisi",
      "Türkiye'nin Jeopolitik Konumu",
      "Bölgesel Kalkınma Projeleri",
      "İklim ve Yer Şekilleri",
      "Ülkeler Arası Etkileşim",
      "Küresel ve Bölgesel Örgütler",
      "Üretim Alanları ve Ulaşım Ağları",
      "Bölgeler ve Ülkeler",
      "Çevre ve Toplum",
      "Doğal Afetler",
    ],
    // KPSS GK — Coğrafya: 18 soru
    kpssKonular: [
      "Türkiye'nin Coğrafi Konumu (1 soru)",
      "Türkiye'nin Fiziki Özellikleri ve Yer Şekilleri (5 soru)",
      "Türkiye'nin İklimi ve Bitki Örtüsü (2 soru)",
      "Türkiye'de Nüfus ve Yerleşme (2 soru)",
      "Tarım ve Hayvancılık (1 soru)",
      "Madenler ve Enerji Kaynakları (2 soru)",
      "Sanayi (2 soru)",
      "Ulaşım (1 soru)",
      "Turizm (2 soru)",
    ],
    kpssGrup: "gk",
  },

  felsefe: {
    key: "felsefe",
    isim: "Felsefe",
    icon: "🤔",
    renk: "#9B59B6",
    tytKonular: [
      "Felsefe'nin Konusu",
      "Bilgi Felsefesi",
      "Varlık Felsefesi",
      "Ahlak Felsefesi",
      "Sanat Felsefesi",
      "Din Felsefesi",
      "Siyaset Felsefesi",
      "Bilim Felsefesi",
      "MÖ 6.yy – MS 2.yy Felsefesi",
      "MS 2.yy – 15.yy Felsefesi",
      "15. – 17.yy Felsefesi",
      "18. – 19.yy Felsefesi",
      "20.yy Felsefesi",
    ],
    // AYT Felsefe Grubu: Mantık + Psikoloji + Sosyoloji
    aytKonular: [
      "Mantığa Giriş",
      "Klasik Mantık",
      "Mantık ve Dil",
      "Sembolik Mantık",
      "Psikoloji Bilimini Tanıyalım",
      "Psikolojinin Temel Süreçleri",
      "Öğrenme, Bellek, Düşünme",
      "Ruh Sağlığının Temelleri",
      "Sosyolojiye Giriş",
      "Birey ve Toplum",
      "Toplumsal Yapı",
      "Toplumsal Değişme ve Gelişme",
      "Toplum ve Kültür",
      "Toplumsal Kurumlar",
    ],
  },

  din_kulturu: {
    key: "din_kulturu",
    isim: "Din Kültürü",
    icon: "🕌",
    renk: "#D4A96A",
    tytKonular: [
      "İnanç",
      "İbadet",
      "Hz. Muhammed",
      "Kur'an ve Yorumu",
      "Ahlak",
      "İslam Düşüncesinde Yorumlar",
      "Din, Kültür ve Medeniyet",
    ],
    aytKonular: [],
  },

  fizik: {
    key: "fizik",
    isim: "Fizik",
    icon: "⚡",
    renk: "#2980B9",
    tytKonular: [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Sıvıların Kaldırma Kuvveti",
      "Basınç",
      "Isı, Sıcaklık ve Genleşme",
      "Hareket",
      "Dinamik",
      "İş, Güç ve Enerji",
      "Elektrik",
      "Optik",
      "Manyetizma",
      "Dalgalar",
    ],
    aytKonular: [
      "Vektörler",
      "Kuvvet, Tork ve Denge",
      "Kütle Merkezi",
      "Basit Makineler",
      "Hareket",
      "Newton'un Hareket Yasaları",
      "İş, Güç ve Enerji",
      "Atışlar",
      "İtme ve Momentum",
      "Elektrik Alan ve Potansiyel",
      "Paralel Levhalar ve Sığa",
      "Manyetik Alan ve Manyetik Kuvvet",
      "İndüksiyon, Alternatif Akım ve Transformatörler",
      "Çembersel Hareket",
      "Kütle Çekim ve Kepler Yasaları",
      "Basit Harmonik Hareket",
      "Dalga Mekaniği ve Elektromanyetik Dalgalar",
      "Atom Modelleri",
      "Büyük Patlama ve Radyoaktivite",
      "Modern Fizik",
      "Modern Fiziğin Teknolojideki Uygulamaları",
    ],
  },

  kimya: {
    key: "kimya",
    isim: "Kimya",
    icon: "⚗️",
    renk: "#27AE60",
    tytKonular: [
      "Kimya Bilimi",
      "Atom ve Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Kimyasal Hesaplamalar",
      "Kimyanın Temel Kanunları",
      "Asit, Baz ve Tuz",
      "Maddenin Halleri",
      "Karışımlar",
      "Doğa ve Kimya",
      "Kimya Her Yerde",
    ],
    aytKonular: [
      "Atom ve Periyodik Sistem",
      "Kimyasal Hesaplamalar",
      "Asit, Baz ve Tuz",
      "Maddenin Halleri",
      "Karışımlar",
      "Kimya Her Yerde",
      "Modern Atom Teorisi",
      "Gazlar",
      "Çözeltiler",
      "Kimyasal Tepkimelerde Enerji",
      "Kimyasal Tepkimelerde Hız",
      "Kimyasal Tepkimelerde Denge",
      "Asit-Baz Dengesi",
      "Çözünürlük Dengesi",
      "Kimya ve Elektrik",
      "Karbon Kimyasına Giriş",
      "Organik Kimya",
    ],
  },

  biyoloji: {
    key: "biyoloji",
    isim: "Biyoloji",
    icon: "🧬",
    renk: "#7EC850",
    tytKonular: [
      "Biyoloji Bilimi",
      "Canlıların Ortak Özellikleri",
      "Canlıların Temel Bileşenleri",
      "Hücre ve Organelleri",
      "Hücre Zarından Madde Geçişi",
      "Canlıların Sınıflandırılması",
      "Mitoz ve Eşeysiz Üreme",
      "Mayoz ve Eşeyli Üreme",
      "Kalıtım",
      "Ekosistem Ekolojisi",
      "Güncel Çevre Sorunları",
    ],
    aytKonular: [
      "Sinir Sistemi",
      "Endokrin Sistem",
      "Duyu Organları",
      "Destek ve Hareket Sistemi",
      "Sindirim Sistemi",
      "Dolaşım ve Bağışıklık Sistemi",
      "Solunum Sistemi",
      "Boşaltım Sistemi",
      "Üriner Sistem",
      "Üreme Sistemi ve Embriyonik Gelişim",
      "Komünite ve Popülasyon Ekolojisi",
      "Nükleik Asitler",
      "Genetik Şifre ve Protein Sentezi",
      "Canlılık ve Enerji",
      "Fotosentez ve Kemosentez",
      "Hücresel Solunum",
      "Bitki Biyolojisi",
      "Canlılar ve Çevre",
    ],
  },

  turk_dili_edebiyati: {
    key: "turk_dili_edebiyati",
    isim: "Türk Dili ve Edebiyatı",
    icon: "📖",
    renk: "#C0392B",
    tytKonular: [],
    aytKonular: [
      "Anlam Bilgisi",
      "Dil Bilgisi",
      "Güzel Sanatlar ve Edebiyat",
      "Metinlerin Sınıflandırılması",
      "Şiir Bilgisi",
      "Edebi Sanatlar",
      "Türk Edebiyatı Dönemleri",
      "İslamiyet Öncesi Türk Edebiyatı ve Geçiş Dönemi",
      "Halk Edebiyatı",
      "Divan Edebiyatı",
      "Tanzimat Edebiyatı",
      "Servet-i Fünun Edebiyatı",
      "Fecr-i Ati Edebiyatı",
      "Milli Edebiyat",
      "Cumhuriyet Şiiri",
      "Cumhuriyet Romanı",
      "Cumhuriyet Dönemi",
      "Edebiyat Akımları",
      "Dünya Edebiyatı",
    ],
  },

  yabanci_dil: {
    key: "yabanci_dil",
    isim: "Yabancı Dil",
    icon: "🌐",
    renk: "#E67E22",
    tytKonular: [],
    aytKonular: [],
  },

  // ─── KPSS'e Özel Dersler ──────────────────────────────────────────────────

  vatandaslik: {
    key: "vatandaslik",
    isim: "Vatandaşlık",
    icon: "⚖️",
    renk: "#2C3E50",
    tytKonular: [],
    aytKonular: [],
    // KPSS GK — Vatandaşlık: 9 soru
    kpssKonular: [
      "Hukukun Temel Kavramları ve Hukuk Kaynakları (1 soru)",
      "Devlet Biçimleri ve Hükümet Sistemleri (1 soru)",
      "Türk Anayasa Tarihi (Kanun-u Esasi → 1982) (1 soru)",
      "1982 Anayasası'nın Temel İlkeleri (1 soru)",
      "Yasama: TBMM Yapısı, Görev ve Yetkileri (1 soru)",
      "Yürütme: Cumhurbaşkanı Görev ve Yetkileri (1 soru)",
      "Yargı: Yüksek Mahkemeler (1 soru)",
      "Temel Hak ve Hürriyetler (1 soru)",
      "İdare Hukuku ve Yerel Yönetimler (1 soru)",
    ],
    kpssGrup: "gk",
  },

  guncel_bilgiler: {
    key: "guncel_bilgiler",
    isim: "Güncel Bilgiler",
    icon: "📰",
    renk: "#E67E22",
    tytKonular: [],
    aytKonular: [],
    // KPSS GK — Güncel Bilgiler: 6 soru
    kpssKonular: [
      "Türkiye'nin Güncel Olayları ve Politikaları (dahil)",
      "Uluslararası Kuruluşlar ve Örgütler (dahil)",
      "Türkiye'nin Önemli Başarıları ve Gelişmeleri (dahil)",
      "UNESCO Dünya Mirası Listesi (dahil)",
      "Spor, Kültür ve Sanat Güncel Olayları (dahil)",
      "Toplam: 6 soru (sınava yakın dönem bilgileri)",
    ],
    kpssGrup: "gk",
  },
};

// ─── TYT dersleri (tüm YKS kategorileri için aynı) ───────────────────────────
export const TYT_DERSLER = [
  "turkce",
  "matematik",
  "geometri",
  "tarih",
  "cografya",
  "felsefe",
  "din_kulturu",
  "fizik",
  "kimya",
  "biyoloji",
];

// ─── YKS Kategori yapısı ─────────────────────────────────────────────────────
export interface KategoriYapi {
  label: string;
  icon: string;
  renk: string;
  aciklama: string;
  tyt: string[];
  ayt: string[];
}

export const KATEGORILER: Record<KategoriAdi, KategoriYapi> = {
  sayisal: {
    label: "Sayısal",
    icon: "🔬",
    renk: "#3498DB",
    aciklama: "MF puan türü · Matematik ağırlıklı",
    tyt: TYT_DERSLER,
    ayt: ["matematik", "geometri", "fizik", "kimya", "biyoloji"],
  },
  ea: {
    label: "Eşit Ağırlık",
    icon: "⚖️",
    renk: "#9B59B6",
    aciklama: "TM puan türü · Sözel + Sayısal",
    tyt: TYT_DERSLER,
    ayt: ["matematik", "geometri", "turk_dili_edebiyati", "tarih", "cografya", "felsefe"],
  },
  dil: {
    label: "Dil",
    icon: "🌍",
    renk: "#E67E22",
    aciklama: "Dil puan türü · Yabancı Dil ağırlıklı",
    tyt: TYT_DERSLER,
    ayt: ["turk_dili_edebiyati", "tarih", "cografya", "felsefe", "yabanci_dil"],
  },
};
